Account/urls.py
from django.conf.urls import  url


from django.contrib.auth import views as auth_views
# from .views import user_view,user_edit,my_profile
from django.conf.urls import url
from django.contrib import admin
from .views import (
	login,
	logout,
	resign,
	)

urlpatterns = [
	# url(r'^$', my_profile, name='my_profiley'),
	# url(r'^edit/$', my_profile, name='edit_my_profiley'),
	# url(r'^(?P<pk>\d+)$', user_view, name='detail'),


	#using system

    url(r'^dang-nhap/$', login, name='login'),
    url(r'^thoat/$', logout,name='logout'),
    url(r'^dang-ky/$', resign,name='resign' ),

]

blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import (
        post_list,
        post_create,
        post_edit,
        post_delete,
        post_detail,
    )
urlpatterns = [
    url(r'^$', post_list,name='list'),
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_edit,name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete,name='delete' ),


]

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static





from django.contrib.auth import views as auth_views


from Account import views as core_views




urlpatterns = [
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # url(r'^$', index,name='home'),
    # url(r'^health$', health),

    # url(r'^account/', include('Account.urls'), namespace='account'),
    url(r'^tai-khoan/',include('Account.urls',namespace='account')),

    url(r'^thong-bao/', include("blog.urls",namespace='blog')),
    #stream balance











    #only use for active...and so on

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Account/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField()
    email_confirmed = models.BooleanField(default=False)
    otp=models.CharField(max_length=6,blank=True)
    balance= models.BigIntegerField(default=99)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    try:
        instance.profile.save()
    except AttributeError:
        profile = Profile.objects.create(user=instance)

        profile.save()

Account/views.py
from django.contrib.auth import (
	authenticate,
	get_user_model,
	login as auth_login,
	logout as auth_logout,
	)
from django.shortcuts import render, redirect
from .form import userloginform,userresignform


def login(request):
	next = request.GET.get("next")
	form=userloginform(request.POST or None)

	context={
		"form":form,
		"title":"login "
		}
	if form.is_valid():
		username=form.cleaned_data.get("username")
		password=form.cleaned_data.get("password")
		user=authenticate(username=username,password=password)
		auth_login(request, user)
		if next:
			return redirect(next)
		else:
			return redirect("/")


	return render(request,"account/login.html",context)

def resign(request):
	title="join with me"
	next = request.GET.get("next")
	form=userresignform(request.POST or None)
	context={
	"title":title,
	"form":form,
	}
	if form.is_valid():
		user=form.save(commit=False)
		password=form.cleaned_data.get("password")
		user.set_password(password)
		user.save()
		new_user=authenticate(username=user.username,password=password)
		auth_login(request,new_user)
		if next:
			return redirect(next)
		else:
			return redirect("/")

	return render(request,"account/signup.html",context)










def logout(request):
	auth_logout(request)
	return render(request,"account/logout.html",{})

Account/templates/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

Account/templates/account_activation_invalid.html
{% extends 'base.html' %}

{% block content %}
  <p>The confirmation link was invalid, possibly because it has already been used.</p>
{% endblock %}

Account/templates/account_activation_sent.html
{% extends 'base.html' %}

{% block content %}
  <p>Please confirm your email address to complete the registration. </p>
{% endblock %}

Account/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h2>Welcome, {{ user.get_full_name }} <small>{{ user.username }}</small>!</h2>
  <p>Thanks for confirming your email address!</p>
{% endblock %}

Account/templates/login.html
{% extends 'base.html' %}

{% block content %}

<style>
.d-flex{
  background:Transparent !important;
}
</style>


  <h1 class="text-center"; style="color:#FFF";>Log in to My Site</h1>
  {% block conntent_main %}
  <div id="content-main" class="d-flex justify-content-center">
  {% if form.errors %}
    <p style="color: red">Your username and password didn't match. Please try again.</p>
  {% endif %}
  <form method="post" >
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% if field.help_text %}
          <p><small style="color: grey">{{ field.help_text }}</small></p>
        {% endif %}
      </p>
    {% endfor %}
    <button type="submit" class="btn btn-secondary">Log in</button>
  <button type="submit" class="btn" backgroundcolor="#4281A4">  <a href={% url 'account:resign' %}>Or
    Sign up </a></button>




  </form>
  <div>
  {% endblock conntent_main%}
{% endblock %}

Account/templates/logout.html
{% extends 'base.html' %}
{% load static %}
{%block content%}
<h1> </h1>




<h1 class="text-center"; style="color:#FFF";>you has been loged out</h1>



<div id="content-main" class="d-flex justify-content-center">




</div>
{%endblock content%}

Account/templates/my_profile.html
{% extends 'base.html' %}
{% load static %}
{%block content%}
<h1> </h1>

<style>
.d-flex{
  background:Transparent !important;
}
</style>


<h1 class="text-center"; style="color:#FFF";>Mypro File</h1>
<div id="content-main" class="d-flex justify-content-center">
  <p>{{user.pk}} </p>
  <p id="log"> {{user.balance}}</p>



</div>
{%endblock content%}

Account/templates/password_change.html
{% extends 'base.html' %}




{% block content %}
<h1 class="text-center"; style="color:#FFF";>Change Password</h1>
<div id="content-main" class="d-flex justify-content-center">



  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-secondary">Change password</button>
      </form>
    </div>
  </div>


  </div>

{% endblock %}

Account/templates/password_change_done.html
{% extends 'base.html' %}



{% block content %}



<h1 class="text-center"; style="color:#FFF";>Your Change Has Been Success </h1>
<div id="content-main" class="d-flex justify-content-center">


  <div class="alert alert-success" role="alert">
    <strong>Success!</strong> Your password has been changed! <a href="{% url 'home' %}"  >Return to home page</a></br>
  </div>

</div>
{% endblock %}

Account/templates/signup.html
{% extends 'base.html' %}

{% block content %}



<style>
.d-flex{
  background:Transparent !important;
}
</style>


<h1 class="text-center"; style="color:#FFF";>Sign up</h1>
<div id="content-main" class="d-flex justify-content-center">

  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit" class="btn btn-secondary">Sign up</button>
  <button type="submit" class="btn" backgroundcolor="#4281A4">  <a href="{% url 'account:login' %}">Or
    Log in </a></button>
  </form>
</div>

{% endblock %}

Account/templates/user_views.html
<h1>another user</h1>
  <p>{{user.user}} </p>
    <p>{{user.pk}} </p>
  <p>{{user.balance}} </p>